project:
  type: book
  output-dir: docs

book:
  title: "Data analysis in Biology"
  author: "Stevie Bain"
  date: ""
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand




